export { default as Hero } from './Hero'
export { default as HowItWorks } from './HowItWorks'
export { default as Rules } from './Rules'
export { default as Categories } from './Categories'
export { default as Testimonials } from './Testimonials'
export { default as FinalCTA } from './FinalCTA'
